# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SignInProject' do
  use_frameworks!

  pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'

  target 'SignInProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SignInProjectUITests' do
    # Pods for testing
  end

end
